AWSRegion: ""
registry:
      pullUrl: ""
      pushUrl: ""
      repositoryName: ""
      accessKey: ""
      accessSecret: ""
storageplan:
    file:
        name: ""
        endPoint: ""
        accessKey: ""
        secretKey: ""
    database:
        name: ""
        host: ""
        port: 5432
        databaseName: ""
        password: ""
        username: ""
ingress:
    className: ""
    domainName: ""
    
