apiVersion: apps/v1
kind: Deployment
metadata:
  name: mendix-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mendix-operator
  template:
    metadata:
      labels:
        name: mendix-operator
    spec:
      serviceAccountName: mendix-operator
      enableServiceLinks: false
      containers:
        - name: mendix-operator
          image: "private-cloud.registry.mendix.com/mendix-operator:2.7.0"
          command:
            - mendix-operator
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mendix-operator"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"