apiVersion: privatecloud.mendix.com/v1alpha1
kind: OperatorConfiguration
metadata:
  name: mendix-operator-configuration
spec:
  buildRuntimeBaseImage: "private-cloud.registry.mendix.com/runtime-base:{{.MxRuntimeVersion}}-rhel"
  buildResources:
    limits:
      cpu: "1"
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 64Mi
  sidecarResources:
    limits:
      cpu: 250m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 16Mi
  metricsSidecarResources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 16Mi
  runtimeResources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  runtimeMetricsConfiguration:
    interval: PT1M
    mode: native
  endpoint:
    type: ingress
    ingress:
      annotations: 
        "{{ .Values.ingress.className }}.ingress.kubernetes.io/proxy-body-size":"500m"
      domain: {{ .Values.ingress.domainName }}
      enableTLS: false
      ingressClassName: {{ .Values.ingress.className }},
      path: "/"
  registry:
    credentials: "mendix-registry-ecr-secret",
    imageNameTemplate: "{{ .Values.registry.repositoryName}}:{{.Name}}",
    pullURL: {{ .Values.registry.pullUrl}},
    pushURL: {{ .Values.registry.pushUrl}},
    type: "ecr"