---
# Secret: registry_secret
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mendix-registry-ecr-secret
stringData:
  credentials: |-
    [default]
    region={{ .Values.AWSRegion}}
    aws_access_key_id={{ .Values.registry.accessKey}}
    aws_secret_access_key={{ .Values.registry.accessSecret}}
type: Opaque
...